name: 'Check Semver Version Number'
description: 'Check if the semver version number has changed from the main branch.'
inputs:
  path:
    required: true
    default: './version.txt'
outputs:
  updated:
    description: 'If the version was updated or not.'

runs:
  using: 'docker'
  image: 'Dockerfile'
