name: Test and Lint
on: [push, pull_request]
jobs:
  test_and_lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04','ubuntu-22.04', 'ubuntu-latest']
        python-version: [ "3.12", "3.x" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analyse with pylint
        run: |
          pylint src --recursive=true --rcfile=.pylintrc
          pylint tests --recursive=true --rcfile=.pylintrc

      - name: Run tests
        run: |
          python3 -m pytest tests

      - name: Run tests and collect coverage
        run: |
          python3 -m pytest tests --cov-report xml:coverage.xml --cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: cloud-coverage.xml
