name: Integration Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main to compare
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: 'main'

      - uses: actions/checkout@v4
        with:
          path: 'branch'
      - name: Self test
        if: ${{ github.ref != 'refs/heads/main' }}
        id: selftest
        uses: khalford/check-version-action@main
        with:
          path: "version.txt"
      - name: Check output
        run: |
          echo "${{ steps.selftest.outputs.updated }}"