name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Self test
        id: selftest
        uses: khalford/check-version-action@main
        with:
          path: "version.txt"
      - name: Check outputs and modified files
        run: |
          echo "${{ steps.selftest.outputs.updated }}"